name: Hello world

on:
    push:
        branches:
            - main

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say hello
              run: echo "Hello, world!"

            - name: Say the date
              run: date

            - name: Say the content
              run: ls -l