name: Deployment Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
        types: [opened, synchronize]

jobs:
    build-and-deploy:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - name: Install dependencies
              run: npm install
            - name: Check style
              run: npm run eslint
            - name: Run build
              run: npm run build
            - name: Trigger deployment
              if: github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip')
              run: curl https://api.render.com/deploy/${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
            - name: Test
              run: npm run test
    
    tag-release:
      needs: [build-and-deploy]
      # skip test
      if: github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip')
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v4
        - name: Bump version and push tag
          uses: anothrNick/github-tag-action@1.73.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DEFAULT_BUMP: patch
